name: Build and Archive Debian Package

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  pull_request:
    paths:
      - 'debian/changelog'

jobs:
  sbuild:
    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}

    runs-on: "${{ vars.RUNS_ON || 'ubuntu-22.04' }}"

    strategy:
      fail-fast: false
      matrix:
        distro: [bullseye]
        arch: [arm64]
        # arch: [armhf,arm64]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: sbuild for ${{ matrix.distro }} ${{ matrix.arch }}
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Archive artifacts and upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: wlanpi-rxg-agent-${{ matrix.distro }}-${{ matrix.arch }}
          path: ${{ steps.build-debian-package.outputs.deb-package }}

