name: Deploy to Packagecloud

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - main
      - master
      - dev
    paths:
      - 'debian/changelog'

jobs:
  check_version:
    name: Check py & deb pkg versions match
    uses: rgnets/wlanpi-gh-workflows/.github/workflows/check-py-deb-pkg-versions-match.yml@main
    with:
      python_version_file_path: 'wlanpi_rxg_agent/__version__.py'
  format:
    name: Get formatted version for filename
    uses: rgnets/wlanpi-gh-workflows/.github/workflows/get-formatted-version-string.yml@main


  sbuild_deploy:
    name: sbuild deploy pkg
    needs:
      - format
      - check_version
    uses: rgnets/wlanpi-gh-workflows/.github/workflows/sbuild-deploy-pkg.yml@main
    with:
      pkg: wlanpi-rxg-agent
      version: ${{ needs.format.outputs.version }}
    secrets: inherit



#
#  sbuild:
#    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}
#
#    runs-on: "${{ vars.RUNS_ON || 'ubuntu-22.04' }}"
#
#    strategy:
#      fail-fast: false
#      matrix:
#        distro: [bullseye]
#        arch: [arm64]
#        # arch: [armhf,arm64]
#
#    environment: PACKAGECLOUD
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: sbuild for ${{ matrix.distro }} ${{ matrix.arch }}
#        uses: wlan-pi/sbuild-debian-package@main
#        id: build-debian-package
#        with:
#          distro: ${{ matrix.distro }}
#          arch: ${{ matrix.arch }}
#
#      - name: Archive artifacts and upload to GitHub
#        uses: actions/upload-artifact@v4
#        with:
#          name: wlanpi-rxg-agent-${{ matrix.distro }}-${{ matrix.arch }}
#          path: ${{ steps.build-debian-package.outputs.deb-package }}
#
#      - name: Upload armhf package to raspbian/${{ matrix.distro }}
#        if: matrix.arch == 'armhf'
#        uses: danielmundi/upload-packagecloud@main
#        with:
#          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
#          packagecloud-username: "${{ vars.PACKAGECLOUD_USER || 'wlanpi' }}"
#          packagecloud-repo: "${{ vars.PACKAGECLOUD_REPO || 'dev' }}"
#          packagecloud-distrib: raspbian/${{ matrix.distro }}
#          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
#
#      - name: Upload arm64 package to debian/${{ matrix.distro }}
#        if: matrix.arch == 'arm64'
#        uses: danielmundi/upload-packagecloud@main
#        with:
#          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
#          packagecloud-username: "${{ vars.PACKAGECLOUD_USER || 'wlanpi' }}"
#          packagecloud-repo: "${{ vars.PACKAGECLOUD_REPO || 'dev' }}"
#          packagecloud-distrib: debian/${{ matrix.distro }}
#          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
